// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.6.12;

import { IERC20 } from "@openzeppelin/contracts-ethereum-package/contracts/token/ERC20/IERC20.sol";

interface IDelayMachine {
    // generated by ..::deposit()
    event PaymentDeposit(uint256 indexed id, address source, address destination, uint256 amount, uint256 expiration);
    // generated by ..::cancel()
    event PaymentCancel(uint256 indexed id, address source, address destination, uint256 amount);
    // generated by ..::withdraw()
    event PaymentWithdraw(uint256 indexed id, address source, address destination, uint256 amount);

    /// @notice Accept a deposit from an account.
    /// @param mocs token quantity
    /// @param expiration the expiration date for this deposit
    /// @return id the transaction id
    function deposit(uint256 mocs, address destination, uint256 expiration) external returns (uint256 id);

    /// @notice Cancel a transaction returning the funds to the source
    /// @param id transaction id
    function cancel(uint256 id) external;

    /// @notice Withdraw stake, send it to the delay machine.
    /// @param id transaction id
    function withdraw(uint256 id) external;

    /// @notice Returns the list of transaction for some account
    /// @return ids transaction ids
    /// @return amounts token quantity
    /// @return expirations expiration dates
    function getTransactions(
        address account
    ) external view returns (uint256[] memory ids, uint256[] memory amounts, uint256[] memory expirations);

    /// @notice Returns the total balance in MOCs for an account
    function getBalance(address account) external view returns (uint256);

    // Public variable
    function getToken() external view returns (IERC20);

    // Public variable
    function getLastId() external view returns (uint256);

    // Public variable
    function getSource() external view returns (address);
}
