// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.6.12;

import { IERC20 } from "@openzeppelin/contracts-ethereum-package/contracts/token/ERC20/IERC20.sol";

/*
    Basic public interface for the supporters smart contract.
    The facade for this contract is the StakingMachine, this interface is specifically for the scheduler
    that needs to call distribute() to distribute the rewards.
*/
interface ISupporters {
    //  generated by supporters::distribute() inside s.lib::_distribute()
    event PayEarnings(uint256 earnings, uint256 start, uint256 end);
    //  generated by supporters::_withdrawFromTo() //when last supporter exits case..
    event CancelEarnings(uint256 earnings, uint256 start, uint256 end);
    // generated by supporters::stakeAt()
    //  supporters::stakeAtFrom()
    //  supporters::stakeAtFromInternal()
    event AddStake(
        address indexed user,
        address indexed subaccount,
        address indexed sender,
        uint256 amount,
        uint256 mocs
    );
    // generated by supporters::withdrawFrom()
    //  supporters::withdrawFromTo()
    event WithdrawStake(
        address indexed user,
        address indexed subaccount,
        address indexed destination,
        uint256 amount,
        uint256 mocs
    );

    //  defined in supporters.sol but not used there neither supporterslib.!!
    // event Withdraw(
    //     address indexed msgSender,
    //     address indexed subacount,
    //     address indexed receiver,
    //     uint256 mocs,
    //     uint256 blockNum
    // );

    /**
      @notice Deposit earnings that will be credited to supporters.
      @dev Earnings will be credited periodically through several blocks.
    */
    function distribute() external;

    /**
      @notice Return true if is ready to do a distribute call

      @return true if ready
    */
    function isReadyToDistribute() external view returns (bool);

    /// @notice The moc token address
    function mocToken() external view returns (IERC20);

    /**
     @notice Return the round length in blocks .
     @dev During each round rewards are collected and distributed during next round.

     @return Number of blocks to distribute earnings
    */
    function period() external view returns (uint256);

    // @notice total amount of mocs inside the supporters contract
    function totalMoc() external view returns (uint256);

    // @notice total amount of tokens inside the supporters contect.
    function totalToken() external view returns (uint256);

    /// @notice Reports the balance of locked MOCs for a specific user.
    /// Delegates to the Supporters smart contract.
    /// @param user user address
    function getLockedBalance(address user) external view returns (uint256);

    /// @notice Reports the balance of locked MOCs for a specific user.
    /// Delegates to the Supporters smart contract.
    /// @param user user address
    /// @return amount the amount of mocs locked
    /// @return untilTimestamp the timestamp that corresponds to the locking date.
    function getLockingInfo(address user) external view returns (uint256 amount, uint256 untilTimestamp);

    /**
       @notice Amount of tokens for _user in a _subaccount.

       @param _user User address
       @param _subaccount subaccount to get balance
       @return tokens for _user at _subaccount
     */
    function getBalanceAt(address _user, address _subaccount) external view returns (uint256);

    /**
      @notice MOC available for withdrawal by _user.

      @param _user User address
      @param _subaccount subaccount to get MOC balance
      @return MOC for _user
    */
    function getMOCBalanceAt(address _user, address _subaccount) external view returns (uint256);

    /**
      @notice Calculate earnings to be paid at a block

      @param _block Block used to calculate
      @return Earnings to be paid
    */
    function getEarningsAt(uint256 _block) external view returns (uint256);

    /**
       @notice Calculate locked earnings at a block

       @param _block Block used for calculations
       @return Locked amount of earnings in MOC
     */
    function getLockedAt(uint256 _block) external view returns (uint256);

    /**
      @notice Return information about earnings

      @return earnings Information about earnings
      @return distributed Currenty distributed
      @return next Will be distributed in next period
    */
    function getEarningsInfo() external view returns (uint256 earnings, uint256 distributed, uint256 next);

    /// @notice Returns the count of whitelisted addresses.
    function getWhiteListLen() external view returns (uint256);

    /**
     @notice Returns the address at index.

     @param _idx index to query.
    */
    function getWhiteListAtIndex(uint256 _idx) external view returns (address);

    /**
     @notice Check if an account is whitelisted

     @param _account The account to check
    */
    function isWhitelisted(address _account) external view returns (bool);

    /**
      Convert amount MOC to equivalent in token

      @param _mocs Amount of MOC
      @return Equivalent amount of tokens
    */
    function mocToToken(uint256 _mocs) external view returns (uint256);

    /**
      Convert amount tokens to equivalent in MOCS

      @param _token Amount of tokens
      @return Equivalent amount of tokens
    */
    function tokenToMoc(uint256 _token) external view returns (uint256);

    /**
       Convert amount tokens to equivalent in MOCS ceiling up

       @param _token Amount of tokens
       @return Equivalent amount of tokens
     */
    function tokenToMocUP(uint256 _token) external view returns (uint256);
}
